"""
LLM Service.

Provides a controlled interface for
LLM-based answer generation.

MOCK_LLM=1 or unset:
    Uses deterministic mock responses.

MOCK_LLM=0:
    Enables the optional real LLM path.
"""

from __future__ import annotations

import os

from config.logging_config import (
    get_logger,
)

from utils.exceptions import (
    LLMServiceError,
)

logger = get_logger(__name__)


class LLMService:
    """
    Provide LLM answer generation.

    The mock implementation is the required
    baseline for the Support Assistant.
    """

    def __init__(self) -> None:
        """
        Initialize the LLM service.
        """

        self.mock_llm = os.getenv(
            "MOCK_LLM",
            "1",
        ) != "0"

        if self.mock_llm:
            logger.info(
                "LLM service initialized in MOCK_LLM mode."
            )
        else:
            logger.info(
                "LLM service initialized in real LLM mode."
            )

    def generate_answer(
        self,
        prompt: str,
    ) -> str:
        """
        Generate an answer using the configured
        LLM mode.

        Parameters
        ----------
        prompt : str
            Structured prompt generated by
            PromptService.

        Returns
        -------
        str
            Generated answer.
        """

        try:

            if self.mock_llm:

                logger.info(
                    "Generating answer using mock LLM."
                )

                return (
                    "Mock LLM response: "
                    "Answer generated using the provided context."
                )

            return self._generate_real_answer(
                prompt,
            )

        except Exception as error:

            logger.exception(
                "LLM answer generation failed."
            )

            raise LLMServiceError(
                str(error),
            ) from error

    def _generate_real_answer(
        self,
        prompt: str,
    ) -> str:
        """
        Optional real LLM implementation.

        This method is intentionally isolated so
        the graded MOCK_LLM path remains independent
        of external API availability.
        """

        raise NotImplementedError(
            "Real LLM integration is optional for Task 3."
        )